### ISSUE TITLE
When will the code be published?

### ISSUE THREAD

**Issue by Suimingzhe** [hxngiee/DiffFace#1]
Thanks for your work on face swapping using diffusion models. When do you plan to publish the code?

Best Regards

**Comment by loboere** [comment]
looks like another dead github project

**Comment by hxngiee** [comment]
> Thanks for your work on face swapping using diffusion models. When do you plan to publish the code?
> 
> Best Regards

Thanks for your interest in this work. Currently, we are discussing with the company about releasing the code. Publishing the code is likely to take longer than expected. Sorry for the delay.
