### ISSUE TITLE
When will the code be open source?

### ISSUE THREAD

**Issue by zhouzikang** [hxngiee/DiffFace#3]
When will the code be open source?

**Comment by zhouzikang** [comment]
@hxngiee

**Comment by hxngiee** [comment]
Apologize for the late reply @zhouzikang @netrunner-exe. We are currently in the process of publishing DiffFace, so it may require some time to release the code. Additionally, we are exploring new ways to further improve the performance of our current model and plan to continue updating it.

As a result, we aim to open the code (with checkpoint files) publicly available before September. I would be grateful if you could wait just a little longer. Thank you.

**Comment by akankshasingh25** [comment]
Hey,
September is here, and still waiting. An update will be good.
