### ISSUE TITLE
Please share the code/trained models for DiffFace 

### ISSUE THREAD

**Issue by thakral-kartik** [hxngiee/DiffFace#8]
Hi,

Can you please share the code of the repo? If that's not possible, please share the trained models for inference.

I really appreciate any help you can provide.

**Comment by thakral-kartik** [comment]
If they share the code/trained models, they could get a lot of hits just like other existing FaceSwap papers, which would increase their visibility and impact in the research community.

**Comment by netrunner-exe** [comment]
> It seems to me that nobody will post anything since the repository has been empty for 8 months. If the authors were interested, they would have done it earlier. It looks like it didn't end up any further than the article for conference.

I take my words back, thanks a lot for releasing the code and models!
